export const GET_EMPLOYEE_TABLE_DATA_REQUEST: string =
  "GET_EMPLOYEE_TABLE_DATA_REQUEST";
export const GET_EMPLOYEE_TABLE_DATA_SUCCESS: string =
  "GET_EMPLOYEE_TABLE_DATA_SUCCESS";
export const GET_EMPLOYEE_TABLE_DATA_FAILURE: string =
  "GET_EMPLOYEE_TABLE_DATA_FAILURE";

export const GET_EMPLOYEE_PROFILE_REQUEST: string =
  "GET_EMPLOYEE_PROFILE_REQUEST";
export const GET_EMPLOYEE_PROFILE_SUCCESS: string =
  "GET_EMPLOYEE_PROFILE_SUCCESS";
export const GET_EMPLOYEE_PROFILE_FAILURE: string =
  "GET_EMPLOYEE_PROFILE_FAILURE";

export const ADD_EMPLOYEE_TABLE_DATA_REQUEST: string =
  "ADD_EMPLOYEE_TABLE_DATA_REQUEST";
export const ADD_EMPLOYEE_TABLE_DATA_SUCCESS: string =
  "ADD_EMPLOYEE_TABLE_DATA_SUCCESS";
export const ADD_EMPLOYEE_TABLE_DATA_FAILURE: string =
  "ADD_EMPLOYEE_TABLE_DATA_FAILURE";
export const ADD_EMPLOYEE_TABLE_DATA_RESET: string =
  "ADD_EMPLOYEE_TABLE_DATA_RESET";

export const EDIT_EMPLOYEE_TABLE_DATA_REQUEST: string =
  "EDIT_EMPLOYEE_TABLE_DATA_REQUEST";
export const EDIT_EMPLOYEE_TABLE_DATA_SUCCESS: string =
  "EDIT_EMPLOYEE_TABLE_DATA_SUCCESS";
export const EDIT_EMPLOYEE_TABLE_DATA_FAILURE: string =
  "EDIT_EMPLOYEE_TABLE_DATA_FAILURE";
export const EDIT_EMPLOYEE_TABLE_DATA_RESET: string =
  "EDIT_EMPLOYEE_TABLE_DATA_RESET";

export const DELETE_EMPLOYEE_TABLE_DATA_REQUEST: string =
  "DELETE_EMPLOYEE_TABLE_DATA_REQUEST";
export const DELETE_EMPLOYEE_TABLE_DATA_SUCCESS: string =
  "DELETE_EMPLOYEE_TABLE_DATA_SUCCESS";
export const DELETE_EMPLOYEE_TABLE_DATA_FAILURE: string =
  "DELETE_EMPLOYEE_TABLE_DATA_FAILURE";
export const DELETE_EMPLOYEE_TABLE_DATA_RESET: string =
  "DELETE_EMPLOYEE_TABLE_DATA_RESET";
